name = "dash-metricas"
pages_build_output_dir = "dist"
compatibility_date = "2025-07-28"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "trafficpro-db"
database_id = "ff8c0c41-a808-4f68-aa1a-505f5c8a4d58"
